# Generated by Django 3.2 on 2023-04-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketdata',
            name='underlying',
            field=models.CharField(max_length=100),
        ),
    ]
