# Generated by Django 3.2 on 2023-04-15 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_marketdata_underlying'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='market_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_name', to='webapp.marketdata'),
        ),
    ]
